name: "Crates.io"

on:
  workflow_run:
    workflows: [ "Tag" ]
    types: [ completed ]
    branches:
      - 'main'

jobs:
  publish-to-crates-io:
    name: "Publish to crates.io"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CRATESIO_TOKEN }}
          ignore-unpublished-changes: true
